-- ═══════════════════════════════════════════════════════════════════════════
-- Janzour monthly rates (Processed_Parcels × Janzour_Stores)
-- Run in Supabase SQL Editor (whole file).
--
-- If you see "relation does not exist": this block creates empty shells so the
-- rest runs. Replace with your real schema + migrate data when ready.
-- If your tables use different names (e.g. processed_parcels lowercase), either
-- rename in DB or change quoted names below to match.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Tables (minimal columns required by stats + join) ─────────────────────
CREATE TABLE IF NOT EXISTS public."Processed_Parcels" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id text NOT NULL,
  status text NOT NULL,
  completion_date timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."Janzour_Stores" (
  store_id text PRIMARY KEY,
  name text,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public."Processed_Parcels" IS 'Finalized parcels; status تم التسليم / مخزن مرتجعات; completion_date for monthly grouping.';
COMMENT ON TABLE public."Janzour_Stores" IS 'Janzour store registry; join Processed_Parcels on store_id.';

-- ── Performance: partial composite index matches filter + join + GROUP BY month ──
-- Planner can seek by store_id and filter by completion_date; partial excludes
-- irrelevant rows early on large tables.
CREATE INDEX IF NOT EXISTS idx_processed_parcels_janzour_agg
  ON public."Processed_Parcels" (store_id, completion_date DESC)
  WHERE completion_date IS NOT NULL
    AND status IN ('تم التسليم', 'مخزن مرتجعات');

-- Standalone btree on completion_date for time-window scans (optional but cheap).
CREATE INDEX IF NOT EXISTS idx_processed_parcels_completion_date
  ON public."Processed_Parcels" (completion_date DESC)
  WHERE completion_date IS NOT NULL
    AND status IN ('تم التسليم', 'مخزن مرتجعات');

-- Janzour store lookup (unique when store_id is the natural key).
CREATE INDEX IF NOT EXISTS idx_janzour_stores_store_id
  ON public."Janzour_Stores" (store_id);


-- ── Aggregated monthly stats (only finalized statuses, Janzour stores only) ──
-- PostgREST RPC from JS sends `{}` → use a single jsonb arg (ignored) for reliable discovery.
DROP FUNCTION IF EXISTS public.get_janzour_monthly_rates();
DROP FUNCTION IF EXISTS public.get_janzour_monthly_rates(jsonb);

CREATE OR REPLACE FUNCTION public.get_janzour_monthly_rates(p_filter jsonb DEFAULT '{}'::jsonb)
RETURNS TABLE (
  year integer,
  month integer,
  total_processed bigint,
  delivered_count bigint,
  returned_count bigint,
  delivery_rate_pct numeric,
  return_rate_pct numeric
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    EXTRACT(YEAR FROM pp.completion_date)::integer AS year,
    EXTRACT(MONTH FROM pp.completion_date)::integer AS month,
    COUNT(*)::bigint AS total_processed,
    COUNT(*) FILTER (WHERE pp.status = 'تم التسليم')::bigint AS delivered_count,
    COUNT(*) FILTER (WHERE pp.status = 'مخزن مرتجعات')::bigint AS returned_count,
    CASE WHEN COUNT(*) > 0
      THEN ROUND((100.0 * COUNT(*) FILTER (WHERE pp.status = 'تم التسليم') / COUNT(*))::numeric, 2)
      ELSE 0::numeric END AS delivery_rate_pct,
    CASE WHEN COUNT(*) > 0
      THEN ROUND((100.0 * COUNT(*) FILTER (WHERE pp.status = 'مخزن مرتجعات') / COUNT(*))::numeric, 2)
      ELSE 0::numeric END AS return_rate_pct
  FROM public."Processed_Parcels" pp
  INNER JOIN public."Janzour_Stores" js ON js.store_id = pp.store_id
  WHERE pp.completion_date IS NOT NULL
    AND pp.status IN ('تم التسليم', 'مخزن مرتجعات')
  GROUP BY EXTRACT(YEAR FROM pp.completion_date), EXTRACT(MONTH FROM pp.completion_date)
  ORDER BY EXTRACT(YEAR FROM pp.completion_date) DESC, EXTRACT(MONTH FROM pp.completion_date) DESC;
$$;

COMMENT ON FUNCTION public.get_janzour_monthly_rates(jsonb) IS
  'Monthly delivered/returned counts for Janzour stores from Processed_Parcels (completion_date). p_filter reserved for future use.';

-- PostgREST / Supabase client access
GRANT EXECUTE ON FUNCTION public.get_janzour_monthly_rates(jsonb) TO anon, authenticated;

-- Refresh PostgREST schema cache (Supabase) so RPC appears immediately
NOTIFY pgrst, 'reload schema';

-- If you prefer SECURITY INVOKER instead (honors RLS on base tables), replace the
-- function with INVOKER and add SELECT policies on "Processed_Parcels" / "Janzour_Stores"
-- for the appropriate roles.
